---
- hosts: all

  gather_facts: no
  connection: local

  tasks:
    - name: verify firewall rules
      shell: "nc -G 5 -w 5 -z  {{ inventory_hostname }} 80"
      register: verify_firewall
    - name: validate firewall rules
      debug: msg="validating firewall rules"
      failed_when: "'FAILED' in verify_firewall"

#  roles:
#    - consolidate-config-files
