---
 - name: verify firewall rules
   shell: "nc -G 5 -w 5 -z  {{ inventory_hostname }} {{ port }}"
   register: verify_firewall
 - name: validate firewall rules
   debug: msg="validating firewall rules"
   failed_when: "'succeeded' not in verify_firewall.stdout"
